[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "main.py"  # Remplacez "main.py" par le nom du module principal de votre application.
author = "LR AS"

[tool.flit.metadata.dependencies]
numpy = "*"
matplotlib = "*"