[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "analyse-cge"
description = "Analyse CGE"
version = "0.1.0"
requires-python = ">=3.8"
authors = [
    { name = "Lise Renaud", email = "lise.renaud77@gmail.com" },
    { name = "Aymeric Schaeffer", email = "schaeffer.aymeric@gmail.com" }
]
dependencies = [
    "matplotlib",
    "numpy"
]
dynamic = ["version"]

[project.urls]  # Optional
"Homepage" = "https://github.com/Athrax/Analyse-CGE-Francais"