[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "analyse_cge"
description = "Analyse CGE"
author = "Lise Renaud, Aymeric Schaeffer"
version = "0.1.0"
dependencies = [
    "matplotlib",
    "numpy"
]