[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "analyse_cge"
authors = [
    { name = "Lise Renaud", email = "lise.renaud77@gmail.com" },
    { name = "Aymeric Schaeffer", email = "schaeffer.aymeric@gmail.com" }
]

readme = "README.md"
requires-python = ">=3.8"
classifiers = ["License :: OSI Approved :: MIT License"]
version = "0.1.0"
description = "Your project description"

[dependencies]
numpy = "*"
matplotlib = "*"