[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "analyse_cge"
author = "LR AS"
version = "0.1.0"
dependencies = [
    "matplotlib",
    "numpy"
]